# Generated by Django 4.2.7 on 2025-08-27 15:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='User ID from external service', max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['username'],
                'indexes': [models.Index(fields=['user_id'], name='likes_sampl_user_id_64f823_idx'), models.Index(fields=['username'], name='likes_sampl_usernam_ec89a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SamplePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='User ID from external service', max_length=100)),
                ('description', models.TextField(help_text='Post description (max 2000 characters)', validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(2000)])),
                ('post_number', models.PositiveIntegerField(help_text='Auto-incrementing post number', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='likes_sampl_user_id_070eee_idx'), models.Index(fields=['post_number'], name='likes_sampl_post_nu_baba0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='likes.samplepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='likes.sampleuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'user'], name='likes_postl_post_id_e45ec1_idx'), models.Index(fields=['post'], name='likes_postl_post_id_6ebcdb_idx'), models.Index(fields=['user'], name='likes_postl_user_id_0970b6_idx'), models.Index(fields=['created_at'], name='likes_postl_created_c5d229_idx')],
                'unique_together': {('post', 'user')},
            },
        ),
    ]
