# Generated by Django 5.2.5 on 2025-08-21 18:33

import django.core.validators
import django.db.models.deletion
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='ID from login service', max_length=100, unique=True)),
                ('username', models.CharField(help_text='Unique username for the user', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Username must be at least 3 characters long'), django.core.validators.MaxLengthValidator(50, 'Username cannot exceed 50 characters')])),
                ('bio', models.TextField(blank=True, help_text='User bio (max 200 characters)', max_length=200, validators=[django.core.validators.MaxLengthValidator(200, 'Bio cannot exceed 200 characters')])),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to=profiles.models.profile_picture_path)),
                ('is_complete', models.BooleanField(default=False, help_text='Whether the profile setup is complete')),
                ('is_public', models.BooleanField(default=True, help_text='Whether the profile is publicly visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=profiles.models.profile_picture_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_history', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Profile Picture',
                'verbose_name_plural': 'Profile Pictures',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='interests.interest')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'User Interest',
                'verbose_name_plural': 'User Interests',
                'ordering': ['-created_at'],
                'unique_together': {('profile', 'interest')},
            },
        ),
    ]
