# Generated by Django 5.2.5 on 2025-08-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('music', 'Music'), ('travel', 'Travel'), ('food', 'Food & Cooking'), ('art', 'Art & Design'), ('fashion', 'Fashion'), ('gaming', 'Gaming'), ('fitness', 'Fitness & Health'), ('books', 'Books & Reading'), ('movies', 'Movies & TV'), ('photography', 'Photography'), ('nature', 'Nature & Outdoors'), ('business', 'Business & Finance'), ('education', 'Education'), ('politics', 'Politics'), ('science', 'Science'), ('history', 'History'), ('languages', 'Languages'), ('crafts', 'Crafts & DIY')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
                'ordering': ['category', 'name'],
            },
        ),
    ]
