# Generated by Django 4.2.7 on 2025-08-23 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='User ID from external service', max_length=100)),
                ('description', models.TextField(help_text='Post description (max 2000 characters)', validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(2000)])),
                ('post_number', models.PositiveIntegerField(help_text='Auto-incrementing post number for uniqueness', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='posts/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='posts.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user_id', '-created_at'], name='posts_post_user_id_b93466_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_number'], name='posts_post_post_nu_c75832_idx'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['post', 'media_type'], name='posts_postm_post_id_fe6096_idx'),
        ),
    ]
