version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=profile_db
      - POSTGRES_USER=profile_user
      - POSTGRES_PASSWORD=profile_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - LOGIN_SERVICE_URL=http://host.docker.internal:8000

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: profile_db
      POSTGRES_USER: profile_user
      POSTGRES_PASSWORD: profile_password
    volumes:
      - profile_postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"

volumes:
  profile_postgres_data:
